django_simple_forum/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import  views

urlpatterns = [
    url(r'^$', views.TopicList.as_view(), name="topic_list"),
    url(r'^register/$', views.IndexView.as_view(), name="signup"),
    url(r'^forum/login/$', views.ForumLoginView.as_view(), name="user_login"),
    url(r'^fb_login/$', views.facebook_login, name="facebook_login"),
    url(r'^gp_login/$', views.google_login, name="google_login"),

    url(r'^topic/add/$', views.TopicAdd.as_view(), name="new_topic"),
    url(r'^topic/(?P<slug>[-\w]+)/update/$', views.TopicUpdateView.as_view(), name="topic_update"),
    url(r'^topic/view/(?P<slug>[-\w]+)/$', views.TopicView.as_view(), name="view_topic"),
    url(r'^topic/like/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicLike.as_view()), name="like_topic"),
    url(r'^topic/follow/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicFollow.as_view()), name="follow_topic"),
    url(r'^topic/votes/(?P<slug>[-\w]+)/up/$', views.TopicVoteUpView.as_view(), name="topic_vote_up"),
    url(r'^topic/votes/(?P<slug>[-\w]+)/down/$', views.TopicVoteDownView.as_view(), name="topic_vote_down"),

    url(r'^mentioned-users/(?P<topic_id>[-\w]+)/$', views.get_mentioned_user, name="get_mentioned_user"),
    url(r'^user/profile/(?P<user_name>[a-zA-Z0-9_.-@]+)/$', views.ProfileView.as_view(), name="view_profile"),
    url(r'^change-password/$', views.UserChangePassword.as_view(), name="user_change_password"),
    url(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password"),
    url(r'^comment/delete/(?P<comment_id>[-\w]+)/$',
        csrf_exempt(views.CommentDelete.as_view()), name="comment_delete"),
    url(r'^comment/edit/(?P<comment_id>[-\w]+)/$', views.CommentEdit.as_view(), name="comment_edit"),

    url(r'^categories/$', views.ForumCategoryList.as_view(), name="forum_categories"),
    url(r'^tags/$', csrf_exempt(views.ForumTagsList.as_view()), name="forum_tags"),
    url(r'^badges/$', csrf_exempt(views.ForumBadgeList.as_view()), name="forum_badges"),
    url(r'^profile/$', views.UserProfileView.as_view(), name="user_profile"),
    url(r'^upload/profile-pic/$', csrf_exempt(views.UserProfilePicView.as_view()), name="user_profile_pic"),
    url(r'^send-mail/settings/$', csrf_exempt(views.UserSettingsView.as_view()), name="user_settings"),

    url(r'^category/(?P<slug>[-\w]+)/$', views.ForumCategoryView.as_view(), name="forum_category_detail"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.ForumTagsView.as_view(), name="forum_tags_detail"),

    url(r'^user/(?P<user_name>[a-zA-Z0-9_-]+.*?)/$', views.UserDetailView.as_view(), name="user_details"),

    url(r'^comment/add/$', views.CommentAdd.as_view(), name="new_comment"),
    url(r'^comment/votes/(?P<pk>[-\w]+)/up/$', views.CommentVoteUpView.as_view(), name="comment_vote_up"),
    url(r'^comment/votes/(?P<pk>[-\w]+)/down/$', views.CommentVoteDownView.as_view(), name="comment_vote_down"),

    #url(r'^dashboard/$', views.LoginView.as_view(), name="dashboard"),
    url(r'^dashboard/$',views.DashboardView.as_view(), name="dashboard"),
    url(r'^logout/$', views.getout, name='out'),

    url(r'^dashboard/category/list/$', csrf_exempt(views.CategoryList.as_view()), name="categories"),
    url(r'^dashboard/category/add/$', views.CategoryAdd.as_view(), name="add_category"),
    url(r'^dashboard/category/delete/(?P<slug>[-\w]+)/$',
        csrf_exempt(views.CategoryDelete.as_view()), name="delete_category"),
    url(r'^dashboard/category/edit/(?P<slug>[-\w]+)/$',
        views.CategoryEdit.as_view(), name="edit_category"),
    url(r'^dashboard/category/view/(?P<slug>[-\w]+)/$',
        views.CategoryDetailView.as_view(), name="view_category"),

    url(r'^dashboard/badge/list/$', csrf_exempt(views.BadgeList.as_view()), name="badges"),
    url(r'^dashboard/badge/add/$', views.BadgeAdd.as_view(), name="add_badge"),
    url(r'^dashboard/badge/delete/(?P<slug>[-\w]+)/$', csrf_exempt(views.BadgeDelete.as_view()), name="delete_badge"),
    url(r'^dashboard/badge/edit/(?P<slug>[-\w]+)/$', views.BadgeEdit.as_view(), name="edit_badge"),
    url(r'^dashboard/badge/view/(?P<slug>[-\w]+)/$', views.BadgeDetailView.as_view(), name="view_badge"),

    url(r'^dashboard/users/list/$', csrf_exempt(views.UserList.as_view()), name="users"),
    url(r'^dashboard/users/delete/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        csrf_exempt(views.DashboardUserDelete.as_view()), name="delete_user"),
    url(r'^dashboard/users/status/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        csrf_exempt(views.UserStatus.as_view()), name="user_status"),
    url(r'^dashboard/users/view/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        views.UserDetail.as_view(), name="user_detail"),
    url(r'^dashboard/users/edit/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        views.DashboardUserEdit.as_view(), name="edit_user"),

    url(r'^dashboard/topics/list/$', views.DashboardTopicList.as_view(), name="topics"),
    url(r'^dashboard/topics/delete/(?P<slug>[-\w]+)/$', views.TopicDeleteView.as_view(), name="delete_topic"),
    url(r'^dashboard/topic/view/(?P<slug>[-\w]+)/$', views.TopicDetail.as_view(), name="topic_detail"),
    url(r'^dashboard/topic/status/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicStatus.as_view()), name="topic_status"),
    url(r'^dashboard/topic/edit/(?P<slug>[-\w]+)/$', views.TopicUpdateView.as_view(), name="topic_update"),

    url(r'^dashboard/change-password/$', views.ChangePassword.as_view(), name="change_password"),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

#app_name = 'django_simple_forum'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('django_simple_forum.urls', 'django_simple_forum'), namespace='django_simple_forum'))
]

django_simple_forum/views.py
import urllib
import requests
try:
    from urllib.parse import urlparse
except ImportError:
    from urlparse import urlparse
from datetime import datetime

from django.contrib.auth import logout, login, load_backend
from django.urls import reverse, reverse_lazy
from django.core.files import File
from django.conf import settings
from django.contrib.auth.hashers import check_password
from django.db.models import Q
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.views.generic import TemplateView, UpdateView, ListView, CreateView, DetailView,\
    DeleteView, View
from django.views.generic.edit import FormView
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.template import Context,loader
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from django.views.decorators.csrf import csrf_exempt

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

#from endless_pagination.views import AjaxListView
#from microurl import google_mini

from .forms import LoginForm
from .models import ForumCategory, STATUS, Badge, Topic, Tags, UserProfile, UserTopics, Timeline,\
    Facebook, Google, Comment, Vote
from .mixins import AdminMixin, LoginRequiredMixin, CanUpdateTopicMixin
from .forms import CategoryForm, BadgeForm, RegisterForm, TopicForm, CommentForm, UserProfileForm,\
    ChangePasswordForm, UserChangePasswordForm, ForgotPasswordForm
#from mpcomp.facebook import GraphAPI, get_access_token_from_code
from .sending_mail import Memail
from .facebook import *



def timeline_activity(user, content_object, namespace, event_type):
    Timeline.objects.create(
        user=user,
        content_object=content_object,
        namespace=namespace,
        event_type=event_type,
    )


class LoginView(FormView):
    template_name = 'dashboard/dashboard_login.html'
    form_class = LoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_superuser:
                return redirect('django_simple_forum:dashboard')
            else:
                return redirect('django_simple_forum:topic_list')
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.get_user()
        if user.is_superuser:
            login(self.request, form.get_user())
            data = {
                'error': False,
                'response': 'You have successfully logged into the dashboard'
            }
        else:
            data = {
                'error': True,
                'response': 'You dont have access to login to dashboard'
            }
        return JsonResponse(data)

    def form_invalid(self, form):
        return JsonResponse({'error': True, 'response': form.errors})


class DashboardView(AdminMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'


def getout(request):
    if not request.user.is_superuser:
        logout(request)
        return HttpResponseRedirect(reverse('django_simple_forum:topic_list'))
    else:
        logout(request)
    return HttpResponseRedirect(reverse('django_simple_forum:dashboard'))

class CategoryList(AdminMixin, ListView):
    model = ForumCategory
    template_name = 'dashboard/categories.html'
    context_object_name = 'categories_list'

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        categories_list = ForumCategory.objects.filter(parent=None)
        context['categories_list'] = categories_list
        return context

    def post(self, request, *args, **kwargs):
        categories_list = self.model.objects.all()

        if request.POST.get('is_active') == 'True':
            categories_list = categories_list.filter(is_active=True)
        if request.POST.get('search_text', ''):
            categories_list = categories_list.filter(
                title__icontains=request.POST.get('search_text')
            )
        return render(request, self.template_name, {'categories_list': categories_list})


class CategoryDetailView(AdminMixin, DetailView):
    model = ForumCategory
    template_name = 'dashboard/view_category.html'
    slug_field = "slug"
    context_object_name = 'category'

    def get_object(self):
        return get_object_or_404(ForumCategory, slug=self.kwargs['slug'])


class CategoryAdd(AdminMixin, CreateView):
    model = ForumCategory
    form_class = CategoryForm
    template_name = "dashboard/category_add.html"
    success_url = '/forum/dashboard/categories/add/'

    def get_form_kwargs(self):
        kwargs = super(CategoryAdd, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        menu = form.save()
        if self.request.POST.get('parent'):
            menu.parent_id = self.request.POST.get('parent')
            menu.save()

        data = {'error': False, 'response': 'Successfully Created Category'}
        return JsonResponse(data)

    def get_success_url(self):
        return redirect(reverse('django_simple_forum:categories'))

    def form_invalid(self, form):
        data = {'error': True, 'response': form.errors}
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super(CategoryAdd, self).get_context_data(**kwargs)
        form = CategoryForm(self.request.GET)
        menus = ForumCategory.objects.filter(parent=None)
        context['form'] = form
        context['menus'] = menus
        return context

class CategoryDelete(AdminMixin, DeleteView):
    model = ForumCategory
    slug_field = 'slug'
    template_name = "dashboard/categories.html"
    success_url = '/forum/dashboard/categories/'

    def get_object(self):
        return get_object_or_404(ForumCategory, slug=self.kwargs['slug'])

    def get_success_url(self):
        return redirect(reverse('django_simple_forum:categories'))

    def post(self, request, *args, **kwargs):
        category = self.get_object()
        category.delete()
        return JsonResponse({'error': False, 'response': 'Successfully Deleted Category'})


class CategoryEdit(AdminMixin, UpdateView):
    model = ForumCategory
    form_class = CategoryForm
    template_name = "dashboard/category_add.html"
    context_object_name = 'category'

    def get_object(self):
        return get_object_or_404(ForumCategory, slug=self.kwargs['slug'])

    def get_form_kwargs(self):
        kwargs = super(CategoryEdit, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        menu = form.save()
        if self.request.POST.get('parent'):
            menu.parent_id = self.request.POST.get('parent')
            menu.save()
        data = {'error': False, 'response': 'Successfully Edited Category'}
        return JsonResponse(data)

    def get_success_url(self):
        return redirect(reverse('django_simple_forum:categories'))

    def form_invalid(self, form):
        return JsonResponse({'error': True, 'response': form.errors})

    def get_context_data(self, **kwargs):
        context = super(CategoryEdit, self).get_context_data(**kwargs)
        form = CategoryForm(self.request.GET)
        menus = ForumCategory.objects.filter(parent=None)
        context['form'] = form
        context['menus'] = menus
        return context

class BadgeList(AdminMixin, ListView):
    model = Badge
    template_name = 'dashboard/badges.html'
    context_object_name = 'badges_list'

    def get_context_data(self, **kwargs):
        context = super(BadgeList, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        badges_list = self.model.objects.all()
        if request.POST.get('search_text', ''):
            badges_list = badges_list.filter(
                Q(title__icontains=request.POST.get('search_text')))
        per_page = request.POST.get("filter_per_page") if request.POST.get(
            "filter_per_page") else 10
        return render(request, self.template_name, {'badges_list': badges_list,
                                                    "per_page": per_page})


class DashboardTopicList(AdminMixin, ListView):
    template_name = 'dashboard/topics.html'
    context_object_name = "topic_list"

    def get_queryset(self):
        queryset = Topic.objects.all()
        search_text = self.request.POST.get('search_text')
        if search_text:
            queryset = queryset.filter(
                Q(title__icontains=search_text) | Q(created_by__username__icontains=search_text)
            )
        return queryset


class BadgeDetailView(AdminMixin, DetailView):
    model = Badge
    template_name = 'dashboard/view_badge.html'
    slug_field = "slug"
    context_object_name = 'badge'

    def get_object(self):
        return get_object_or_404(Badge, slug=self.kwargs['slug'])


class BadgeAdd(AdminMixin, CreateView):
    model = Badge
    form_class = BadgeForm
    template_name = "dashboard/badge_add.html"

    def get_form_kwargs(self):
        kwargs = super(BadgeAdd, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.save()
        data = {'error': False, 'response': 'Successfully Created Badge'}
        return JsonResponse(data)

    def get_success_url(self):
        return redirect(reverse('django_simple_forum:badges'))

    def form_invalid(self, form):
        return JsonResponse({'error': True, 'response': form.errors})

    def get_context_data(self, **kwargs):
        context = super(BadgeAdd, self).get_context_data(**kwargs)

django_simple_forum/templates/forum/badges.html
{% extends 'forum/base.html' %}
{% block stage %}
   <div class="main_container">
     <div class="container">
        <div class="row middle_container">
          {% include 'forum/left_menu.html' %}
          <div class="main_left_container col-md-9 col-md-pull-3 col-sm-9 col-sm-pull-3 col-sm-8 col-xs-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <!-- category section starts here-->
             <div class="Users_container row">
               <h3 class="create_topic_heading">All Badges</h3>
               <div class="row">
                 <div class="badges_row">
                 {% for badge in badges_list %}
                  <div class="col-md-4 col-sm-4 badge_item">
                    <div class="badge_content">
                      <div class="title"><a href="#">{{ badge.title }}</a></div>
                      <div class="content">{{ badge.description }}</div>
                      <span class="count">{{badge.get_users|length}}</span>
                    </div>
                  </div>
                  {% endfor %}
                  </div>
               </div>
              </div>
              <!-- category section ends here-->
              </div>
            </div>
          </div>
        </div>
     </div>
   </div>
{% endblock %}

django_simple_forum/templates/forum/categories.html
{% extends 'forum/base.html' %}
{% block stage %}
<div class="main_container">
  <div class="container">
    <div class="row middle_container">
      {% include 'forum/left_menu.html' %}
      <div class="main_left_container col-md-9 col-md-pull-3 col-sm-9 col-sm-pull-3 col-sm-8 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <!-- category section starts here-->
            <div class="Users_container  row">
              <h3 class="create_topic_heading">All Categories</h3>
              <div class="user_table_row category_row">
                <div class="table-responsive">
                {% if categories %}
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Topics</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for category in categories %}
                      <tr>
                        <td><a href="{% url "django_simple_forum:forum_category_detail" category.slug %}" class="disclosure" style='background:{{ category.color }}!important;'>{{category.title}}</a></td>
                        <td>{{category.description|safe}}</td>
                        <td><a href="#">{{ category.get_topics|length }}</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                {% else %}
                  No Categories Available Here
                {% endif %}
                </div>
              </div>
            </div>
            <!-- category section ends here-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

django_simple_forum/templates/forum/left_menu.html
{% load forum_tags %}
<div class="main_right_container col-md-3 col-md-push-9 col-sm-3 col-sm-push-9 col-sm-4  col-xs-12 ">
             <div class="fixed_right">
               <div class="panel panel-default right_panel">
                <div class="panel-heading">
                  <h3 class="panel-title all_cat">All Categories <span class="pull-right hidden-md hidden-sm hidden-lg"><i class="fa fa-chevron-down" aria-hidden="true"></i></span></h3>
                </div>
                <div class="panel-body off">
                  <ul class="category_items">
                    {% get_categories as categories %}
                    {% for category in categories %}
                    <li class="category_item"><a href="{% url "django_simple_forum:forum_category_detail" category.slug %}" class="disclosure" style="background:{{category.color}}!important;"> {{ category.title }} </a></li>
                    {% endfor %}
                    <li class="category_item"><a href="{% url "django_simple_forum:forum_categories" %}" class="disclosure"> All </a></li>
                  </ul>
                </div>
              </div>
              <div class="panel panel-default right_panel">
                <div class="panel-heading">
                  <h3 class="panel-title all_cat">All Tags  <span class="pull-right hidden-md hidden-sm hidden-lg"><i class="fa fa-chevron-down" aria-hidden="true"></i></span></h3>
                </div>
                <div class="panel-body off">
                  <ul class="category_tags">
                    {% get_tags as tags %}
                  {% for tag in tags %}
                    <li class="tag_item"><a href="{% url "django_simple_forum:forum_tags_detail" tag.slug %}">{{ tag.title }}</a>
                  {% endfor %}
                  </li>
                  <li class="tag_item"><a href="{% url "django_simple_forum:forum_tags" %}">All Tags</a>
                  </ul>
                </div>
              </div>
              {% if badges %}
              <div class="panel panel-default right_panel">
                <div class="panel-heading">
                  <h3 class="panel-title all_cat">ALl Badges  <span class="pull-right hidden-md hidden-sm hidden-lg"><i class="fa fa-chevron-down" aria-hidden="true"></i></span></h3>
                </div>
                <div class="panel-body off">
                  <ul class="badges">
                  {% get_badges as badges %}
                  {% for badge in badges %}
                    <li class="badge_item"><a class="testlink" href="">{{ badge.title }}<span class="badge">{{ badge.get_users|length }}</span></a></li>
                  {% endfor %}
                    <li class="badge_item"><a href="{% url "django_simple_forum:forum_badges" %}" class="all">All Badges </a></li>
                  </ul>
                </div>
              </div>
              {% endif %}
             </div>
          </div>

django_simple_forum/templates/forum/tags.html
{% extends 'forum/base.html' %}
{% block stage %}
<div class="main_container">
   <div class="container">
      <div class="row middle_container">
        {% include 'forum/left_menu.html' %}
          <div class="main_left_container col-md-9 col-md-pull-3 col-sm-9 col-sm-pull-3 col-sm-8 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <!-- category section starts here-->
           <div class="new_topic_container tags_container row">
             <h3 class="create_topic_heading">All Tags</h3>
              <form name="tagsform" id="tagsform" method="post">
                {% csrf_token %}
                <input type="hidden" name="alphabet_value" id="alphabet_value">
                <button type="submit" style="display:none;"></button>
              </form>

             <!-- Tags_list starts here -->
             <div class="tag_list">
                <ul class="list-inline">
                  <li><a href="#" class="all">All</a></li>
                  <li><a href="#" class="a">A</a></li>
                  <li><a href="#" class="b">B</a></li>
                  <li><a href="#" class="c">C</a></li>
                  <li><a href="#" class="d">D</a></li>
                  <li><a href="#" class="e">E</a></li>
                  <li><a href="#" class="f">F</a></li>
                  <li><a href="#" class="g">G</a></li>
                  <li><a href="#" class="h">H</a></li>
                  <li><a href="#" class="i">I</a></li>
                  <li><a href="#" class="j">J</a></li>
                  <li><a href="#" class="k">K</a></li>
                  <li><a href="#" class="l">L</a></li>
                  <li><a href="#" class="m">M</a></li>
                  <li><a href="#" class="n">N</a></li>
                  <li><a href="#" class="o">O</a></li>
                  <li><a href="#" class="p">P</a></li>
                  <li><a href="#" class="q">Q</a></li>
                  <li><a href="#" class="r">R</a></li>
                  <li><a href="#" class="s">S</a></li>
                  <li><a href="#" class="t">T</a></li>
                  <li><a href="#" class="u">U</a></li>
                  <li><a href="#" class="v">V</a></li>
                  <li><a href="#" class="w">W</a></li>
                  <li><a href="#" class="x">X</a></li>
                  <li><a href="#" class="y">Y</a></li>
                  <li><a href="#" class="z">Z</a></li>
                </ul>
             </div>
             <!-- tags_list ends here -->
                <!-- Discussion-create container starts here -->
                  <div class="discussion-Tags-container">
                    <div class="tags-block">
                        <div class="row tag-list no_row_margin">
                        {% for tag in tags %}
                          <a href="{% url "django_simple_forum:forum_tags_detail" tag.slug %}">{{ tag.title }} <small>{{ tag.get_topics|length }}</small></a>
                        {% endfor %}
                        </div>
                    </div>
                  </div>
                <!-- Discussion-create container ends here -->
            </div>
            <!-- category section ends here-->
            </div>
          </div>
        </div>
      </div>
   </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.list-inline li a').click(function(e){
    e.preventDefault();
    $('#alphabet_value').val($(this).attr('class'));
    $('#tagsform').submit();
});
</script>
{% endblock %}

django_simple_forum/templates/forum/topic_delete.html
{% extends 'forum/base.html' %}

{% block stage %}
	<form action="" method="POST">
		{% csrf_token %}
		<p>
			Are you sure you want to delete Topic <b>"{{ object }}"</b> in category <b>{{ topic.category }}</b> ?
		</p>
		<input type="submit" name="">
	</form>
{% endblock %}

django_simple_forum/templates/forum/topic_list.html
{% extends 'forum/base.html' %}
{% load static %}

{% block stage %}
<div class="main_container">
     <div class="container">
        <div class="row middle_container">
          {% include 'forum/left_menu.html' %}
          <div class="main_left_container col-md-9 col-md-pull-3 col-sm-9 col-sm-pull-3 col-sm-8 col-xs-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="topic_container">
                 <!-- topic_block starts here -->
                  <h3 class="create_topic_heading">All Topics <span class="pull-right sort_options">{% if request.user.is_authenticated %}<a href="{% url "django_simple_forum:new_topic" %}">New Topic</a>{% endif %}</span></h3>
                 {% for topic in topic_list %}
                  <div class="topic_block">
                    <div class="topic_title">
                    <a href="{% url "django_simple_forum:view_topic" topic.slug %}">{{ topic.title }}</a>
                    </div>
                    <div class="topic_options">
                     <span class="category"><a href="#" class="gaming">{{ topic.category.title }} </a></span><span class="activity">Updated on {{ topic.updated_on }}</span>
                    <span class="reply"><a href="#"><i class="fa fa-reply"></i>Replies {{ topic.get_all_comments.count }} </a></span>
                    <!-- <span class="views"><a href="#"><i class="fa fa-eye"></i> Views {{ topic.no_of_views }} </a></span> -->
                    </div>
                    <div class="topic_users">
                      <ul class="users_list">
                        {% for user in topic.get_topic_users %}
                        <li><a href="{% url "django_simple_forum:user_details" user.user.username %}" title="{{ user.user.username }}"><img src="{% if user.profile_pic %}{% else %}//d2pt99vxm3n8bc.cloudfront.net/static/dummy.jpg{% endif %}"></a></li>
                        {% endfor %}
                      </ul>
                      {% if topic.created_by == request.user %}
                        <a href="{% url 'django_simple_forum:topic_update' topic.slug %}"> Update</a>
                        <a href="{% url 'django_simple_forum:delete_topic' topic.slug %}"> delete </a>
                      {% endif %}
                    </div>
                     <br clear="all">
                  </div>
                {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
     </div>
   </div>
{% endblock %}

django_simple_forum/templates/forum/topics_list.html
{% load endless %}
{% paginate topic_list %}

{% for topic in topic_list %}
  <div class="topic_block">
    <div class="topic_title">
    <a href="#">{{ topic.title }}</a>
    </div>
    <div class="topic_options">
     <span class="category"><a href="#" class="gaming">{{ topic.category.title }} </a></span><span class="activity">Updated on {{ topic.updated_on }}</span>
    <span class="reply"><a href="#"><i class="fa fa-reply"></i>Replies 123 </a></span>
    <span class="views"><a href="#"><i class="fa fa-eye"></i> Views {{ topic.no_of_views }} </a></span>
    <span class="likes"><a href="#"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Likes {{ topic.no_of_likes }} </a></span>
    </div>
    <div class="topic_users">
      <ul class="users_list">
        <li><a href="#"><img src="http://newwallpapershd.com/wp-content/uploads/2014/10/3D-Birds-Live-Wallpaper-App-for-Android.jpg"></a></li>
         <li><a href="#"><img src="http://4.bp.blogspot.com/-BItXd_Lt-5I/VdtyEROhPwI/AAAAAAAAEEs/tE4ZzobMb3o/s1600/beautiful%2Bbirds%2Bwallpapers%2Bfree%2Bdownload%2B%25285%2529.jpg"></a></li>
         <li><a href="#"><img src="http://www.magazinefuse.com/wp-content/uploads/2015/07/20_Birds-of-Paradise-4340x2718-1024x640.jpg"></a></li>
         <li><a href="#"><img src="http://www.magazinefuse.com/wp-content/uploads/2015/07/1-birds_pcheloedki-1920x1200-1024x640.jpg"></a></li>
          <li><a href="#"><img src="http://widewallpaper.info/wp-content/uploads/2016/02/COOL-WALLPAPER-HIGH-DEFINITION-WLF1009.jpg"></a></li>
         <li><a href="#"><img src="http://www.hdwallpaperspop.com/wp-content/uploads/2016/03/garfield-cool-hd-wallpaper.jpeg"></a></li>
      </ul>
    </div>
     <br clear="all">
  </div>
{% endfor %}

<div class="pagination">
    {% show_pages %}</div>