django_simple_forum/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import  views

urlpatterns = [
    url(r'^$', views.TopicList.as_view(), name="topic_list"),
    url(r'^register/$', views.IndexView.as_view(), name="signup"),
    url(r'^forum/login/$', views.ForumLoginView.as_view(), name="user_login"),
    url(r'^fb_login/$', views.facebook_login, name="facebook_login"),
    url(r'^gp_login/$', views.google_login, name="google_login"),

    url(r'^topic/add/$', views.TopicAdd.as_view(), name="new_topic"),
    url(r'^topic/(?P<slug>[-\w]+)/update/$', views.TopicUpdateView.as_view(), name="topic_update"),
    url(r'^topic/view/(?P<slug>[-\w]+)/$', views.TopicView.as_view(), name="view_topic"),
    url(r'^topic/like/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicLike.as_view()), name="like_topic"),
    url(r'^topic/follow/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicFollow.as_view()), name="follow_topic"),
    url(r'^topic/votes/(?P<slug>[-\w]+)/up/$', views.TopicVoteUpView.as_view(), name="topic_vote_up"),
    url(r'^topic/votes/(?P<slug>[-\w]+)/down/$', views.TopicVoteDownView.as_view(), name="topic_vote_down"),

    url(r'^mentioned-users/(?P<topic_id>[-\w]+)/$', views.get_mentioned_user, name="get_mentioned_user"),
    url(r'^user/profile/(?P<user_name>[a-zA-Z0-9_.-@]+)/$', views.ProfileView.as_view(), name="view_profile"),
    url(r'^change-password/$', views.UserChangePassword.as_view(), name="user_change_password"),
    url(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password"),
    url(r'^comment/delete/(?P<comment_id>[-\w]+)/$',
        csrf_exempt(views.CommentDelete.as_view()), name="comment_delete"),
    url(r'^comment/edit/(?P<comment_id>[-\w]+)/$', views.CommentEdit.as_view(), name="comment_edit"),

    url(r'^categories/$', views.ForumCategoryList.as_view(), name="forum_categories"),
    url(r'^tags/$', csrf_exempt(views.ForumTagsList.as_view()), name="forum_tags"),
    url(r'^badges/$', csrf_exempt(views.ForumBadgeList.as_view()), name="forum_badges"),
    url(r'^profile/$', views.UserProfileView.as_view(), name="user_profile"),
    url(r'^upload/profile-pic/$', csrf_exempt(views.UserProfilePicView.as_view()), name="user_profile_pic"),
    url(r'^send-mail/settings/$', csrf_exempt(views.UserSettingsView.as_view()), name="user_settings"),

    url(r'^category/(?P<slug>[-\w]+)/$', views.ForumCategoryView.as_view(), name="forum_category_detail"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.ForumTagsView.as_view(), name="forum_tags_detail"),

    url(r'^user/(?P<user_name>[a-zA-Z0-9_-]+.*?)/$', views.UserDetailView.as_view(), name="user_details"),

    url(r'^comment/add/$', views.CommentAdd.as_view(), name="new_comment"),
    url(r'^comment/votes/(?P<pk>[-\w]+)/up/$', views.CommentVoteUpView.as_view(), name="comment_vote_up"),
    url(r'^comment/votes/(?P<pk>[-\w]+)/down/$', views.CommentVoteDownView.as_view(), name="comment_vote_down"),

    #url(r'^dashboard/$', views.LoginView.as_view(), name="dashboard"),
    url(r'^dashboard/$',views.DashboardView.as_view(), name="dashboard"),
    url(r'^logout/$', views.getout, name='out'),

    url(r'^dashboard/category/list/$', csrf_exempt(views.CategoryList.as_view()), name="categories"),
    url(r'^dashboard/category/add/$', views.CategoryAdd.as_view(), name="add_category"),
    url(r'^dashboard/category/delete/(?P<slug>[-\w]+)/$',
        csrf_exempt(views.CategoryDelete.as_view()), name="delete_category"),
    url(r'^dashboard/category/edit/(?P<slug>[-\w]+)/$',
        views.CategoryEdit.as_view(), name="edit_category"),
    url(r'^dashboard/category/view/(?P<slug>[-\w]+)/$',
        views.CategoryDetailView.as_view(), name="view_category"),

    url(r'^dashboard/badge/list/$', csrf_exempt(views.BadgeList.as_view()), name="badges"),
    url(r'^dashboard/badge/add/$', views.BadgeAdd.as_view(), name="add_badge"),
    url(r'^dashboard/badge/delete/(?P<slug>[-\w]+)/$', csrf_exempt(views.BadgeDelete.as_view()), name="delete_badge"),
    url(r'^dashboard/badge/edit/(?P<slug>[-\w]+)/$', views.BadgeEdit.as_view(), name="edit_badge"),
    url(r'^dashboard/badge/view/(?P<slug>[-\w]+)/$', views.BadgeDetailView.as_view(), name="view_badge"),

    url(r'^dashboard/users/list/$', csrf_exempt(views.UserList.as_view()), name="users"),
    url(r'^dashboard/users/delete/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        csrf_exempt(views.DashboardUserDelete.as_view()), name="delete_user"),
    url(r'^dashboard/users/status/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        csrf_exempt(views.UserStatus.as_view()), name="user_status"),
    url(r'^dashboard/users/view/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        views.UserDetail.as_view(), name="user_detail"),
    url(r'^dashboard/users/edit/(?P<user_id>[a-zA-Z0-9_-]+.*?)/$',
        views.DashboardUserEdit.as_view(), name="edit_user"),

    url(r'^dashboard/topics/list/$', views.DashboardTopicList.as_view(), name="topics"),
    url(r'^dashboard/topics/delete/(?P<slug>[-\w]+)/$', views.TopicDeleteView.as_view(), name="delete_topic"),
    url(r'^dashboard/topic/view/(?P<slug>[-\w]+)/$', views.TopicDetail.as_view(), name="topic_detail"),
    url(r'^dashboard/topic/status/(?P<slug>[-\w]+)/$', csrf_exempt(views.TopicStatus.as_view()), name="topic_status"),
    url(r'^dashboard/topic/edit/(?P<slug>[-\w]+)/$', views.TopicUpdateView.as_view(), name="topic_update"),

    url(r'^dashboard/change-password/$', views.ChangePassword.as_view(), name="change_password"),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

#app_name = 'django_simple_forum'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('django_simple_forum.urls', 'django_simple_forum'), namespace='django_simple_forum'))
]

django_simple_forum/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
import hashlib
from datetime import datetime

STATUS = (
    ('Draft', 'Draft'),
    ('Published', 'Published'),
    ('Disabled', 'Disabled'),
)

USER_ROLES = (
    ('Admin', 'Admin'),
    ('Publisher', 'Publisher'),
)

User = settings.AUTH_USER_MODEL


# tags created for topic
class Tags(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, unique=True)

    def get_topics(self):
        topics = Topic.objects.filter(tags__in=[self], status='Published')
        return topics


# tags created for topic
class Badge(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, unique=True)

    def get_users(self):
        user_profile = UserProfile.objects.filter(badges__in=[self])
        return user_profile


def img_url(self, filename):
    hash_ = hashlib.md5()
    hash_.update(
        str(filename).encode('utf-8') + str(datetime.now()).encode('utf-8'))
    file_hash = hash_.hexdigest()
    return "%s%s/%s" % (self.file_prepend, file_hash, filename)


# user profile to store no of votes available to user, badges for a topic, user roles,
class UserProfile(models.Model):
    file_prepend = "forum_user/profilepics/"
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    used_votes = models.IntegerField(default='0')
    user_roles = models.CharField(choices=USER_ROLES, max_length=10)
    badges = models.ManyToManyField(Badge)
    profile_pic = models.FileField(
        max_length=500, null=True, blank=True, upload_to=img_url)
    send_mailnotifications = models.BooleanField(default=False)

    # need to add social details for a user if we implement socail login

    def get_no_of_up_votes(self):
        user_topics = UserTopics.objects.filter(user=self.user)
        votes = 0
        for topic in user_topics:
            votes += topic.no_of_votes
        return votes

    def get_no_of_down_votes(self):
        user_topics = UserTopics.objects.filter(user=self.user)
        votes = 0
        for topic in user_topics:
            votes += topic.no_of_down_votes
        return votes

    def get_topics(self):
        topics = Topic.objects.filter(created_by=self.user)
        return topics

    def get_followed_topics(self):
        topics = UserTopics.objects.filter(user=self.user, is_followed=True)
        topics = Topic.objects.filter(id__in=topics.values_list('topic', flat=True))
        return topics

    def get_liked_topics(self):
        topics = UserTopics.objects.filter(user=self.user, is_like=True)
        topics = Topic.objects.filter(id__in=topics.values_list('topic', flat=True))
        return topics

    def get_timeline(self):
        timeline = Timeline.objects.filter(user=self.user).order_by('-created_on')
        return timeline

    def get_user_topic_tags(self):
        tags = Tags.objects.filter(id__in=self.get_topics().values_list('tags', flat=True))
        return tags

    def get_user_topic_categories(self):
        categories = ForumCategory.objects.filter(id__in=self.get_topics().values_list('category', flat=True))
        return categories
        # return []

    def get_user_suggested_topics(self):
        categories = ForumCategory.objects.filter(id__in=self.get_topics().values_list('category', flat=True))
        topics = Topic.objects.filter(category__id__in=categories.values_list('id', flat=True))
        return topics
        # return []


class ForumCategory(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    is_active = models.BooleanField(default=False)
    color = models.CharField(max_length=20, default="#999999")
    is_votable = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=1000)
    description = models.TextField()
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def get_topics(self):
        topics = Topic.objects.filter(category=self, status='Published')
        return topics

    def __str__(self):
        return self.title


class Vote(models.Model):
    TYPES = (
        ("U", "Up"),
        ("D", "Down"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(choices=TYPES, max_length=1)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

class Topic(models.Model):
    title = models.CharField(max_length=2000)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, max_length=10)
    category = models.ForeignKey(ForumCategory, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now=True)
    no_of_views = models.IntegerField(default='0')
    slug = models.SlugField(max_length=1000)
    tags = models.ManyToManyField(Tags)
    no_of_likes = models.IntegerField(default='0')
    votes = models.ManyToManyField(Vote)

    def get_comments(self):
        comments = Comment.objects.filter(topic=self, parent=None)
        return comments

    def get_all_comments(self):
        comments = Comment.objects.filter(topic=self)
        return comments

    def get_last_comment(self):
        comments = Comment.objects.filter(topic=self).order_by('-updated_on').first()
        return comments

    def get_topic_users(self):
        comment_user_ids = Comment.objects.filter(topic=self).values_list('commented_by', flat=True)
        liked_users_ids = UserTopics.objects.filter(topic=self, is_like=True).values_list('user', flat=True)
        followed_users = UserTopics.objects.filter(topic=self, is_followed=True).values_list('user', flat=True)
        all_users = list(comment_user_ids) + list(liked_users_ids) + list(followed_users) + [self.created_by.id]
        users = UserProfile.objects.filter(user_id__in=set(all_users))
        return users

    # def get_total_of_votes(self):
    #     no_of_votes = self.no_of_votes + self.no_of_down_votes
    #     return no_of_votes

    def up_votes_count(self):
        return self.votes.filter(type="U").count()

    def down_votes_count(self):
        return self.votes.filter(type="D").count()  

    def __str__(self):
        return self.title      

# user followed topics
class UserTopics(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    is_followed = models.BooleanField(default=False)
    followed_on = models.DateField(null=True, blank=True)
    no_of_votes = models.IntegerField(default='0')
    no_of_down_votes = models.IntegerField(default='0')
    is_like = models.BooleanField(default=False)


class Comment(models.Model):
    comment = models.TextField(null=True, blank=True)
    commented_by = models.ForeignKey(User, related_name="commented_by", on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, related_name="topic_comments", on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey("self", blank=True, null=True, related_name="comment_parent",on_delete=models.CASCADE)
    mentioned = models.ManyToManyField(User, related_name="mentioned_users")
    votes = models.ManyToManyField(Vote)

    def get_comments(self):
        comments = self.comment_parent.all()
        return comments

    def up_votes_count(self):
        return self.votes.filter(type="U").count()

    def down_votes_count(self):
        return self.votes.filter(type="D").count()


# user activity
class Timeline(models.Model):
    content_type = models.ForeignKey(ContentType, related_name="content_type_timelines", on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    namespace = models.CharField(max_length=250, default="default", db_index=True)
    event_type = models.CharField(max_length=250, db_index=True)
    user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)
    data = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        index_together = [("content_type", "object_id", "namespace"), ]
        ordering = ['-created_on']


class Attachment(models.Model):
    file_prepend = "forum_topic/attachments/"
    uploaded_by = models.ForeignKey(User, related_name='attachments_user', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    attached_file = models.FileField(
        max_length=500, null=True, blank=True, upload_to=img_url)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class Facebook(models.Model):
    user = models.ForeignKey(User, related_name='user_facebook', on_delete=models.CASCADE)
    facebook_id = models.CharField(max_length=100)
    facebook_url = models.CharField(max_length=200, default='')
    first_name = models.CharField(max_length=200, default='')
    last_name = models.CharField(max_length=200, default='')
    verified = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    language = models.CharField(max_length=200, default='')
    hometown = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)
    gender = models.CharField(max_length=200, default='')
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, default='')

django_simple_forum/templates/dashboard/badges.html
{% extends 'dashboard/dashboard_base.html' %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Badges List <span class="pull-right"><a href="{% url "django_simple_forum:add_badge" %}" class=""><i class="fa fa-user-plus view"></i>New Badge</a></span></label>
    </div>
    <div class="results-slct-items row mt">
      <div class="col-md-6 col-xs-6 page-items">
        Per Page
        <select id="pagination_per_page">
        <option value="10" {% if per_page == "10" %}selected{% endif %}>10</option>
        <option value="20" {% if per_page == "20" %}selected{% endif %}>20</option>
        <option value="50" {% if per_page == "50" %}selected{% endif %}>40</option>
        <option value="100" {% if per_page == "100" %}selected{% endif %}>40</option>
        </select>
      </div>
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if badges_list %}
    <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody class="overflow:scroll;">
                        {% for badge in badges_list %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td>{{ badge.id }}</td>
                          <td>{{ badge.title }}</td>
                          <td><a href="{% url "django_simple_forum:view_badge" badge.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_badge" badge.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_badge" badge.slug %}" class="delete-badge"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    
      </div>
    </div>
    <nav class="overview-paging">
    </nav>
        {% else %}
    No Badge Available in database
    {% endif %}

  </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.delete-badge').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to delete Badge?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
      if (data.error) {
        alert(data.response);
      } else {
        alert("Badge Deleted Successfully")
        window.location = '.';
      }
    }, 'json');
  });

</script>
{% endblock %}

django_simple_forum/templates/dashboard/categories.html
{% extends 'dashboard/dashboard_base.html' %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Categories <span class="pull-right"><a href="{% url "django_simple_forum:add_category" %}" class=""><i class="fa fa-user-plus view"></i>New Category</a></span></label>
    </div>
    <div class="results-slct-items row mt">
      <div class="col-md-6 col-xs-6 page-items">
        Per Page
        <select id="pagination_per_page">
        <option value="10" {% if per_page == "10" %}selected{% endif %}>10</option>
        <option value="20" {% if per_page == "20" %}selected{% endif %}>20</option>
        <option value="50" {% if per_page == "50" %}selected{% endif %}>40</option>
        <option value="100" {% if per_page == "100" %}selected{% endif %}>40</option>
        </select>
      </div>
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if categories_list %}
        <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Color</th>
                          <th>Created By</th>
                          <th>Is Votable</th>
                          <th>Is Active</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody class="overflow:scroll;">
                        {% for category in categories_list %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td>{{ forloop.counter }}</td>
                          <td>{%if category.parent%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{%endif%}{{ category.title }}</td>
                          <td><input type="color" name="color" id="color" value="{{ category.color }}" disabled></td>
                          <td>{{ category.created_by }}</td>
                          <td>{% if category.is_votable %}True{% else %}False{% endif %}</td>
                          <td>{% if category.is_active %}True{% else %}False{% endif %}</td>
                          <td><a href="{% url "django_simple_forum:view_category" category.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_category" category.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_category" category.slug %}" class="delete-category"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% for sub_category in category.forumcategory_set.all %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td></td>
                          <td>{%if sub_category.parent%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{%endif%}{{ sub_category.title }}</td>
                          <td><input type="color" name="color" id="color" value="{{ sub_category.color }}" disabled></td>
                          <td>{{ sub_category.created_by }}</td>
                          <td>{% if sub_category.is_votable %}True{% else %}False{% endif %}</td>
                          <td>{% if sub_category.is_active %}True{% else %}False{% endif %}</td>
                          <td><a href="{% url "django_simple_forum:view_category" sub_category.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_category" sub_category.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_category" sub_category.slug %}" class="delete-category"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% endfor %}

                        {% endfor %}
                      </tbody>
                    </table>
                    
    </div>
    </div>
    <nav class="overview-paging">
    </nav>
        {% else %}
    No Categories Available in database
    {% endif %}

  </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.delete-category').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to delete Category?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
          if (data.error) {
            alert(data.response);
          } else {
            alert("Category Deleted Successfully")
            window.location = '.';
          }
        }, 'json');
  });

</script>
{% endblock %}

django_simple_forum/templates/dashboard/dashboard.html
{% extends 'dashboard/dashboard_base.html' %}

django_simple_forum/templates/dashboard/topics.html
{% extends 'dashboard/dashboard_base.html' %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Topics</label>
    </div>
    <div class="results-slct-items row mt">
      <div class="col-md-6 col-xs-6 result-items">
      </div>
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if topic_list %}
        <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Title</th>
          <th>Created By</th>
          <th>No Of Likes</th>
          <th>No Of Users</th>
          <th>No Of Votes</th>
          <th>No Of Comments</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="overflow:scroll;">
        {% for topic in topic_list %}
        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
          <td>{{ topic.id }}</td>
          <td>{{ topic.title }}</td>
          <td>{{ topic.created_by }}</td>
          <td>{{ topic.no_of_likes }}</td>
          <td>{{ topic.get_topic_users|length }}</td>
          <td>{{ topic.no_of_votes }}</td>
          <td>{{ topic.topic_comments.all|length }}</td>
          <td><a href="{% url "django_simple_forum:topic_detail" topic.slug %}" class=""><i class="fa fa-eye view"></i></a>
            <a data-href="{% url "django_simple_forum:topic_status" topic.slug %}" class="topic-status" title="{% ifequal topic.status 'Draft' %}Draft{% endifequal %}{% ifequal topic.status 'Published' %}Published{% endifequal %}{% ifequal topic.status 'Disabled' %}Disabled{% endifequal %}">{% ifequal topic.status 'Draft' %}<i class='fa fa-floppy-o draft view'></i>{% endifequal %}{% ifequal topic.status 'Published' %}<i class='fa fa-newspaper-o published edit'></i>{% endifequal %}{% ifequal topic.status 'Disabled' %}<i class='fa fa-exclamation-triangle disabled'></i>{% endifequal %}</a>
            <a href="{% url "django_simple_forum:topic_update" topic.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_topic" topic.slug %}" class="delete-topic"><i class="fa fa-trash delete"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    </div>
    <nav class="overview-paging">
    </nav>
    {% else %}
    No Topics Available in database
    {% endif %}
  </div>
</div>
{% endblock %}
{% block extra_js %}
{% csrf_token %}
<script type="text/javascript">
  $('.delete-topic').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to delete Topic?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
      if (data.error) {
        alert(data.response);
      } else {
        alert("Topic Deleted Successfully")
        window.location = '.';
      }
    }, 'json');
  });
  $('.topic-status').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to change the status of topic?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
  		console.log(data);
      if (data.error) {
        alert(data.response);
      } else {
        alert("Topic Status Changed Successfully")
        window.location = '.';
      }
    }, 'json');
  });

</script>
{% endblock %}